dataset_name: crop_type_mapping
data_path: ./data/CropTypeMapping
num_classes: 4
img_size: 64
multi_temporal: true
multi_modal: true
bands:
  s2:
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8a
    - B11
    - B12
data_loader:
  batch: 2
  num_workers: 0
  pin_memory: False
  prefetch_factor: null
  persistent_workers: False