train:
  - ${augmentation.segpreprocessor}
  - _target_: geofm_bench.engine.data_preprocessor.NormalizeMeanStd
  - _target_: geofm_bench.engine.data_preprocessor.ResizeToEncoder
test:
  - _target_: geofm_bench.engine.data_preprocessor.SegPreprocessor
  - _target_: geofm_bench.engine.data_preprocessor.NormalizeMeanStd
  - _target_: geofm_bench.engine.data_preprocessor.ResizeToEncoder
