encoder_name: SSL4EO_Data2Vec_Encoder
foundation_model_name: ssl4eo_data2vec_beit_small_patch16_224
encoder_weights: ./pretrained_models/B13_vits16_data2vec_0099_ckpt.pth
download_url: https://drive.google.com/uc?id=1VbIGBwzZYndv4v1vx9FiD6IP-YwsHEns&export=download&confirm=yes

temporal_input: False

num_layers: 12
embed_dim: 384
input_size: 224

encoder_model_args:
  img_size: 224
  in_chans: 13
  embed_dim: 384
  patch_size: 16
  num_heads: 6
  depth: 12
  mlp_ratio: 4

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11
