encoder_name: SSL4EO_MAE_SAR_Encoder
foundation_model_name: ssl4eo_mae_vit_small_patch16
encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/B2_vitb16_mae_ep99.pth
download_url: https://drive.google.com/uc?id=1QTBKl1asxgQCNd6bO2azXZNPfoQ3Sazv&export=download&confirm=yes

temporal_input: False

num_layers: 12
embed_dim: 768
input_size: 224

encoder_model_args:
  img_size: 224
  in_chans: 2
  embed_dim: 768
  patch_size: 16
  num_heads: 6
  depth: 12
  mlp_ratio: 4

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12
  sar:
    - VV
    - VH

output_layers:
  - 3
  - 5
  - 7
  - 11
