train: 
  - _target_: geofm_bench.engine.data_preprocessor.SegPreprocessor
    # overwritten in run
    dataset: null
    foundation_model: null

  - _target_: geofm_bench.engine.data_preprocessor.NormalizeMeanStd
    # overwritten in run
    dataset: null
    foundation_model: null

  - _target_: geofm_bench.engine.data_preprocessor.ResizeToEncoder
    # overwritten in run
    dataset: null
    foundation_model: null

test: 
  - _target_: geofm_bench.engine.data_preprocessor.SegPreprocessor
    # overwritten in run
    dataset: null
    foundation_model: null

  - _target_: geofm_bench.engine.data_preprocessor.NormalizeMeanStd
    # overwritten in run
    dataset: null
    foundation_model: null

  - _target_: geofm_bench.engine.data_preprocessor.ResizeToEncoder
    # overwritten in run
    dataset: null
    foundation_model: null

