trainer:
  _target_: geofm_bench.engine.trainer.SegTrainer
  # params overwritten in run
  model: null
  train_loader: null
  optimizer: null
  lr_scheduler: null
  evaluator: null
  exp_dir: null
  device: null
  criterion: null

  # params to adapt
  n_epochs: 80
  precision: fp32
  ckpt_interval: 10
  eval_interval: 10
  log_interval: 5
  use_wandb: false

evaluator:
  null
