segmentor_name: UPerNet
task_name: semantic-segmentation
#task_model_args:
  #num_frames: 1
  #mt_strategy: "ltae" #activated only when if num_frames > 1
  #num_classes - task parameter passed from the dataset config
  #wave_list - task parameter passed from the dataset config

channels: 512

loss: cross_entropy






