encoder_name: dofa
encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/DOFA_ViT_base_e100.pth

encoder_model_args:
  img_size: 224
  embed_dim: 768

input_bands:
  s2:
    - B4
    - B3
    - B2

