encoder_name: satlas_pretrain
encoder_weights: null

encoder_model_args:
  model_identifier: Sentinel2_SwinB_SI_RGB #Sentinel2_SwinB_SI_RGB
  fpn: False
  head: null
  num_categories: null
  img_size: 128

input_bands:   # should correctly correspond to the model identifier
  s2:
    - B4
    - B3
    - B2