gfm_encoder:
  encoder_name: dofa
  encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/DOFA_ViT_base_e100.pth
  encoder_model_args:
    img_size: 224
    # in_chans: 3
    embed_dim: 768
  encoder_train_params:
    bands:
      - B2
      - B3
      - B4
    mask_ratio: 0.
    random_cropping: true
task:
  task_model_name: upernet
  task_model_args:
    embed_dim: 768
    num_frames: 1
    t_patch_size: 1
    patch_size: 16
    img_size: 224
    # in_chans: 3
    encoder_type: dofa
    wave_list: [1,1,1]
  task_train_params:
    mode: train
    epochs: 80
    input_channels: 13
    output_channels: 15
    weight_param: 1.03
    label_smoothing: 0.0
    clip_grad: null
    lr: 2.0e-4
    decay: 0
    reduce_lr_on_plateau: 0
    lr_steps: [45,65]
    eval_every: 1
  data_loader:
    batch: 2
    num_workers: 0
    pin_memory: False
    prefetch_factor: null
    persistent_workers: False



