gfm_encoder:
  encoder_name: gfm_swin
  encoder_weights: /geomatics/gpuserver-0/yjia/pretrained_models/gfm.pth
  encoder_model_args:
    embed_dim: 128
    img_size: 128
    in_chans: 3
    depths: [ 2, 2, 18, 2 ]
    num_heads: [ 4, 8, 16, 32 ]
    patch_size: 4
    window_size: 4
    drop_path_rate: 0.1
  encoder_train_params:
    bands:
      - B2
      - B3
      - B4
task:
  task_model_name: upernet
  task_model_args:
    embed_dim: 1024
    num_frames: 1
    t_patch_size: 1
    patch_size: 16
    img_size: 128
    encoder_type: gfm_swin
  task_train_params:
    mode: train
    epochs: 80
    input_channels: 11
    output_channels: 15
    weight_param: 1.03
    label_smoothing: 0.0
    clip_grad: null
    lr: 2.0e-4
    decay: 0
    reduce_lr_on_plateau: 0
    lr_steps: [45,65]
    eval_every: 1
  data_loader:
    batch: 2
    num_workers: 0
    pin_memory: False
    prefetch_factor: 2
    persistent_workers: False



