encoder_config: configs/models_config/prithvi.yaml
dataset_config: configs/datasets_config/mados.yaml
task_config: configs/tasks_config/upernet.yaml
mode: train
epochs: 80
weight_param: 1.03
label_smoothing: 0.0
clip_grad: null
lr: 2.0e-4
decay: 0
reduce_lr_on_plateau: 0
lr_steps: [45,65]
eval_every: 1
resume_from: null   
