gfm_encoder:
  encoder_name: &encoder_name satlas_pretrain
  encoder_weights: /geomatics/gpuserver-0/yjia/pretrained_models/sentinel2_swinb_si_rgb.pth
  encoder_model_args:
    num_channels: 3
    multi_image: False
    backbone: Backbone.SWINB
  encoder_train_params:
    bands:
      - B2
      - B3
      - B4
    data_mean:
      - 775.2290211032589
      - 1080.992780391705
      - 1228.5855250417867
      - 2497.2022620507532
      - 2204.2139147975554
      - 1610.8324823273745
    data_std:
      - 1281.526139861424
      - 1270.0297974547493
      - 1399.4802505642526
      - 1368.3446143747644
      - 1291.6764008585435
      - 1154.505683480695
    mask_ratio: 0.75
    random_cropping: true
task:
  task_model_name: upernet
  task_model_args:
    num_frames: 1
    t_patch_size: 1
    patch_size: 16
    img_size: 240
    # in_chans: 6
    num_classes: 15
    encoder_type: *encoder_name
  task_train_params:
    mode: train
    epochs: 80
    input_channels: 3
    output_channels: 15
    weight_param: 1.03
    label_smoothing: 0.0
    clip_grad: null
    lr: 2.0e-4
    decay: 0
    reduce_lr_on_plateau: 0
    lr_steps: [45,65]
    eval_every: 1
  data_loader:
    batch: 2
    num_workers: 1
    pin_memory: False
    prefetch_factor: 2
    persistent_workers: False
dataset:
  dataset_name: crop_type_mapping

