gfm_encoder:
  encoder_name: ssl4eo_mae
  encoder_weights: /geomatics/gpuserver-0/vmarsocci/pretrained_models/B13_vits16_mae_0099.pth
  encoder_model_args:
    img_size: 224
    in_chans: 13
    embed_dim: 384
  encoder_train_params:
    bands:
      - B1
      - B2
      - B3
      - B4
      - B5
      - B6
      - B7
      - B8
      - B8a
      - B9
      - B10
      - B11
      - B12
    mask_ratio: 0.
    random_cropping: true
task:
  task_model_name: upernet
  task_model_args:
    embed_dim: 384
    num_frames: 1
    t_patch_size: 1
    patch_size: 16
    img_size: 224
    # in_chans: 3
    encoder_type: ssl4eo_mae
  task_train_params:
    mode: train
    epochs: 80
    input_channels: 3
    output_channels: 15
    weight_param: 1.03
    label_smoothing: 0.0
    clip_grad: null
    lr: 2.0e-4
    decay: 0
    reduce_lr_on_plateau: 0
    lr_steps: [45,65]
    eval_every: 1
  data_loader:
    batch: 2
    num_workers: 0
    pin_memory: False
    prefetch_factor: null
    persistent_workers: False



