train: false
work_dir: "" #"/cluster/scratch/user/" #-> ADAPT IF RUNNING ON CLUSTER WITH LIMITED HOME DISK SPACE
seed: 234
use_wandb: false

# TRAINING
num_workers: 1
batch_size: 8


# EXPERIMENT
use_final_ckpt: false
finetune: false
ckpt_dir: ???


