train: false
work_dir: ""
use_wandb: false



# TRAINING
seed: 234
num_workers: 1
batch_size: 8
precision: fp32
ckpt_interval: 10
eval_interval: 10
log_interval: 5


# EXPERIMENT
finetuning: false
ckpt_path: null
limited_label: 1
n_epochs: 80







defaults:
  - dataset: ???
  - foundation_model: ???
  - adaptor: ???
  - _self_ 
