train: true
work_dir: ""
seed: 234
use_wandb: false

# TRAINING
num_workers: 1
batch_size: 8



# EXPERIMENT
finetune: false
ckpt_dir: null
limited_label: 1
n_epochs: 80


defaults:
  - task: ???
  - dataset: ???
  - foundation_model: ???
  - adaptor: ???
  - augmentation: ???
  - criterion: ???
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 
