train: true
work_dir: ""
use_wandb: false
seed: 234


# 
# TRAINING
num_workers: 1
batch_size: 8


# EXPERIMENT
finetune: false
ckpt_dir: null
limited_label: 1
n_epochs: 80


defaults:
  - dataset: ???
  - foundation_model: ???
  - adaptor: ???
  - augmentation: ???
  - _self_ 
