train: true
work_dir: ""
seed: 234

# 
# TRAINING
num_workers: 1
batch_size: 8


# EXPERIMENT
finetune: false
ckpt_dir: null
limited_label: 1
n_epochs: 80


defaults:
  - trainer: ???
  - dataset: ???
  - foundation_model: ???
  - adaptor: ???
  - augmentation: ???
  - criterion: ???
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 
