train:
  encoder_config: null
  dataset_cofig: null
  task_config: null
  epochs: 80
  # output_channels: 15  # remove this to task params
  weight_param: 1.03
  label_smoothing: 0.0
  clip_grad: null
  lr: 2.0e-4
  decay: 0
  reduce_lr_on_plateau: 0
  lr_steps: [45,65]
  eval_every: 1
  resume_from: null    # should support resume training both from config and from args 
