train:
  SegPreprocessor: ~
  RandomFlip:
    ignore_modalities: []
    ud_probability: 0.3
    lr_probability: 0.3
  GammaAugment:
    ignore_modalities: []
    probability: 0.3
    gamma_range: [0.5, 1.5]
  ColorAugmentation:
    ignore_modalities: []
    brightness: 0.2
    contrast: 0.2
    br_probability: 0.3
    ct_probability: 0.3

  # RandomRotation:
  #   ignore_modalities: []
  #   degrees: 10
  # RandomCrop:
  #   ignore_modalities: []
  #   size: [220, 220]
  # Resize:
  #   ignore_modalities: []
  #   size: [224, 224]

test:
  SegPreprocessor: ~